# Generated by Django 4.2.8 on 2023-12-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestinskilldonated',
            name='skill_donated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_donated', to='volunteer.skilldonated'),
        ),
    ]
