# Generated by Django 4.2.8 on 2023-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='charity/profiles/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='volunteer/profiles/'),
        ),
    ]
