# Generated by Django 4.2.8 on 2023-12-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_charity_profile_pic_volunteer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='profile_pic',
            field=models.ImageField(default='/media/charity/profiles/default.jpg', upload_to='charity/profiles/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(default='/media/volunteer/profiles/default.jpg', upload_to='volunteer/profiles/'),
        ),
    ]
